# Generated by Django 3.0.5 on 2020-04-30 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderproducts',
        ),
        migrations.AddField(
            model_name='order',
            name='orderproducts',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product'),
            preserve_default=False,
        ),
    ]
