# Generated by Django 3.0.5 on 2020-05-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20200501_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderproducts',
        ),
        migrations.AddField(
            model_name='order',
            name='orderproducts',
            field=models.ManyToManyField(to='ecommerce.Cart'),
        ),
    ]
