# Generated by Django 3.0.5 on 2020-05-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20200501_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderproducts',
            field=models.ManyToManyField(default=0, to='ecommerce.Cart'),
        ),
    ]
