# Generated by Django 3.0.5 on 2020-05-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_auto_20200507_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='payment',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
