# Generated by Django 3.0.5 on 2020-05-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_order_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderstatus',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
